#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
REGISTRY=https://registry.npmjs.org
GITHUB_REPO=LamplitIsles/dsh-plugins
TEMP_ROOT=""

usage() {
  printf 'Usage: %s [--plan] <public-package-name|directory>\n' "${0##*/}"
  printf 'Bootstrap from a local commit; no merge or push is required.\n'
  printf '%s\n' '--plan prints the proposed versions without network access or changes.'
}
die() { printf '%sError: %s%s\n' "$RED" "$1" "$RESET" >&2; exit 1; }

if [[ ${1:-} == --help ]]; then usage; exit 0; fi
PLAN_ONLY=false
if [[ ${1:-} == --plan ]]; then PLAN_ONLY=true; shift; fi
if [[ $# -ne 1 ]]; then usage >&2; exit 2; fi
if [[ $PLAN_ONLY == false && ! -t 0 ]]; then
  printf 'This wizard requires interactive stdin. Run it directly in a terminal.\n' >&2
  exit 2
fi
command -v node >/dev/null || die 'Install Node.js >=24.11.0 first.'
node -e 'const [major, minor] = process.versions.node.split(".").map(Number); process.exit(major > 24 || (major === 24 && minor >= 11) ? 0 : 1)' || die 'Use Node.js >=24.11.0.'

# release-shared.ts uses only Node built-ins; Node 24 can strip its types without
# installing workspace dependencies just to inspect a package's release plan.
PLAN=$(node --input-type=module - "$ROOT_DIR" "$1" <<'NODE'
import { pathToFileURL } from 'node:url';
import { join } from 'node:path';
import { readFileSync } from 'node:fs';
const [root, selector] = process.argv.slice(2);
const { packageFor, checkReleaseManifest, versionFromTag } = await import(pathToFileURL(join(root, 'scripts/release-shared.ts')));
const entry = packageFor(selector);
if (!entry) throw new Error('Select one registered public workspace package.');
const manifestPath = join(root, 'packages', entry.directory, 'package.json');
const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
const version = versionFromTag(`v${manifest.version}`);
if (version.includes('+')) throw new Error('Bootstrap versions with build metadata need an explicit release plan.');
const errors = checkReleaseManifest(root, entry, `v${version}`);
if (errors.length) throw new Error(errors.join('\n'));
console.log(JSON.stringify({
  name: entry.name, directory: entry.directory, manifestPath,
  currentVersion: version,
  bootstrapVersion: version.includes('-') ? version : `${version}-beta.0`,
  stableVersion: version.split('-')[0],
}, null, 2));
NODE
)
if [[ $PLAN_ONLY == true ]]; then printf '%s\n' "$PLAN"; exit 0; fi
mapfile -t fields < <(node -e 'const p=JSON.parse(process.argv[1]); for(const k of ["name","directory","manifestPath","currentVersion","bootstrapVersion","stableVersion"]) console.log(p[k]);' "$PLAN")
PACKAGE_NAME=${fields[0]}
PACKAGE_DIR=${fields[1]}
CURRENT_VERSION=${fields[3]}
BOOTSTRAP_VERSION=${fields[4]}
STABLE_VERSION=${fields[5]}

for executable in npm corepack pnpm git tar curl; do
  command -v "$executable" >/dev/null || die "Install $executable first."
done
cd "$ROOT_DIR"
[[ $(corepack pnpm --version) == 12.3.4 ]] || die 'Use Corepack pnpm 12.3.4.'
TEMP_ROOT=$(mktemp -d "${TMPDIR:-/tmp}/dsh-npm-bootstrap.XXXXXXXX")
cleanup() { rm -rf -- "$TEMP_ROOT"; }
trap cleanup EXIT

# Only an explicit npm E404 means absent. Network/auth/parse errors stop the run.
npm_lookup() {
  if npm view "$1" "$2" --json --registry="$REGISTRY" \
    --prefer-online --fetch-retries=1 --fetch-timeout=30000 \
    > "$TEMP_ROOT/registry.json" 2> "$TEMP_ROOT/registry.err"; then
    cat "$TEMP_ROOT/registry.json"
  elif node -e 'try{const r=JSON.parse(require("node:fs").readFileSync(process.argv[1],"utf8"));process.exit(r.error?.code==="E404"?0:1)}catch{process.exit(1)}' "$TEMP_ROOT/registry.json"; then
    printf 'null\n'
  else
    die 'npm lookup failed. Check registry connectivity and account access, then rerun.'
  fi
}
registry_status() {
  local result
  result=$(npm_lookup "$PACKAGE_NAME@$1" version) || return 1
  node -e '
    const value = JSON.parse(process.argv[1]);
    if (value === null) console.log("missing");
    else if (value === process.argv[2]) console.log("published");
    else throw new Error("npm returned an unexpected version.");
  ' "$result" "$1"
}
await_registry() {
  local attempt status
  for attempt in {1..12}; do
    status=$(registry_status "$BOOTSTRAP_VERSION")
    [[ $status == published ]] && return 0
    note "Waiting for npm propagation ($attempt/12)…"
    sleep 5
  done
  die 'npm has not exposed the version yet. Do not republish now; rerun later to check first.'
}

banner "First npm publication — $PACKAGE_NAME"

stage "Confirm the bootstrap version"
say "Bootstrap: $PACKAGE_NAME@$BOOTSTRAP_VERSION (public beta tag)."
say "Stable version candidate: $STABLE_VERSION; the later version PR will check main and npm."
note 'No secret is captured. npm login manages its own local authentication.'
STABLE_STATUS=$(registry_status "$STABLE_VERSION")
if [[ $STABLE_STATUS == published ]]; then
  say "$PACKAGE_NAME@$STABLE_VERSION already exists. Use the ordinary version-PR release process."
  exit 0
fi
BOOTSTRAP_STATUS=$(registry_status "$BOOTSTRAP_VERSION")
versions=$(npm_lookup "$PACKAGE_NAME" versions)
node -e '
  const value = JSON.parse(process.argv[1]);
  const versions = value === null ? [] : Array.isArray(value) ? value : [value];
  if (versions.some(version => version !== process.argv[2])) throw new Error("This package has other published versions. Use ordinary releases, not first-publication bootstrap.");
' "$versions" "$BOOTSTRAP_VERSION"
stage "Verify npm account access"
BOOTSTRAP_STATUS=$(registry_status "$BOOTSTRAP_VERSION")
if [[ $BOOTSTRAP_STATUS == published ]]; then
  note 'Bootstrap already exists; npm CLI login is unnecessary for this rerun.'
else
  if account=$(npm whoami --registry="$REGISTRY" 2>/dev/null); then
    note "Authenticated to npm as $account."
  else
    step 'Complete npm browser login and 2FA with an account that can publish under @lamplitisles.'
    npm login --auth-type=web --registry="$REGISTRY"
    account=$(npm whoami --registry="$REGISTRY")
    note "Authenticated to npm as $account."
  fi
  note 'whoami verifies login, not scope authorization. No token or CI secret is collected.'
fi

stage "Validate and prepare the tarball"
BOOTSTRAP_STATUS=$(registry_status "$BOOTSTRAP_VERSION")
if [[ $BOOTSTRAP_STATUS == published ]]; then
  note 'The exact version exists; skipping the completed bootstrap validation.'
else
  if ! git diff --quiet || ! git diff --cached --quiet; then
    die 'Commit source changes locally before bootstrap. No push or merge is required.'
  fi
  source_sha=$(git rev-parse HEAD)
  BUILD_ROOT="$TEMP_ROOT/workspace"
  mkdir -p "$BUILD_ROOT"
  git archive "$source_sha" | tar -x -C "$BUILD_ROOT"
  TEMP_MANIFEST="$BUILD_ROOT/packages/$PACKAGE_DIR/package.json"
  [[ -f $TEMP_MANIFEST ]] || die 'The selected package is not in the local commit yet.'
  note "Preparing local commit $source_sha in a temporary workspace."
  if [[ $CURRENT_VERSION != "$BOOTSTRAP_VERSION" ]]; then
    if ! confirm "Set only the TEMPORARY $PACKAGE_NAME manifest to $BOOTSTRAP_VERSION; leave this checkout unchanged"; then
      die 'No version changed or published. Rerun when ready.'
    fi
    node - "$TEMP_MANIFEST" "$CURRENT_VERSION" "$BOOTSTRAP_VERSION" <<'NODE'
const fs = require('node:fs');
const [path, expected, version] = process.argv.slice(2);
const manifest = JSON.parse(fs.readFileSync(path, 'utf8'));
if (manifest.version !== expected) throw new Error('Committed package version differs from the plan.');
manifest.version = version;
fs.writeFileSync(path, JSON.stringify(manifest, null, 2) + '\n');
NODE
  fi
  DSH_CLI=${DSH_CLI:-$(command -v dsh || true)}
  [[ -n $DSH_CLI ]] || die 'Set DSH_CLI to an existing official DSH 0.1.2-rc.1 executable.'
  # Resolve a pnpm shell shim to the official JavaScript CLI for the smoke gates.
  DSH_CLI=$(node -e '
    const { resolve, dirname } = require("node:path");
    const { existsSync } = require("node:fs");
    const entry = resolve(process.argv[1]);
    const candidate = resolve(dirname(entry), "..", "@deepseek-ai/dsh/lib/bin.js");
    console.log(existsSync(candidate) ? candidate : entry);
  ' "$DSH_CLI")
  export DSH_CLI
  [[ $("$DSH_CLI" --version) == 0.1.2-rc.1 ]] || die 'Expected official DSH 0.1.2-rc.1.'
  (
    cd "$BUILD_ROOT"
    corepack pnpm install --frozen-lockfile
    corepack pnpm run lint
    corepack pnpm run format:check
    corepack pnpm run typecheck
    corepack pnpm run test
    corepack pnpm run build
    corepack pnpm run pack:check
    BOOTSTRAP_STATUS=$(registry_status "$BOOTSTRAP_VERSION")
    if [[ $BOOTSTRAP_STATUS == missing ]]; then
      corepack pnpm exec tsx scripts/publish-preflight.ts "$PACKAGE_NAME" "v$BOOTSTRAP_VERSION"
      corepack pnpm run release:prepare -- "$PACKAGE_NAME" "v$BOOTSTRAP_VERSION" "$TEMP_ROOT/artifact"
    fi
  )
fi

stage "Publish the bootstrap prerelease"
BOOTSTRAP_STATUS=$(registry_status "$BOOTSTRAP_VERSION")
if [[ $BOOTSTRAP_STATUS == published ]]; then
  note 'Already published; skipping this completed stage.'
else
  [[ -n ${BUILD_ROOT:-} ]] || die 'No validated temporary build is available.'
  (cd "$BUILD_ROOT" && corepack pnpm exec tsx scripts/publish-preflight.ts "$PACKAGE_NAME" "v$BOOTSTRAP_VERSION")
  shopt -s nullglob
  artifacts=("$TEMP_ROOT/artifact/"*.tgz)
  [[ ${#artifacts[@]} == 1 ]] || die 'Expected one validated tarball.'
  say "Artifact: ${artifacts[0]}"
  if ! confirm "Publish $PACKAGE_NAME@$BOOTSTRAP_VERSION publicly with tag beta? Publication cannot be undone"; then
    die 'Not published. Rerun later to validate and confirm again.'
  fi
  if npm publish "${artifacts[0]}" --registry="$REGISTRY" --access public --tag beta; then
    await_registry
  else
    warn 'Publication failed; stopping without retrying.'
    die 'If npm reported E404 after whoami succeeded, verify scope ownership/publish permission. Rerun to check registry state before retrying.'
  fi
fi

stage "Verify the public release workflow"
open_url "https://github.com/$GITHUB_REPO/actions/workflows/publish.yml"
# curl follows the user's environment proxy. Node fetch without proxy opt-in
# timed out here on WSL even while npm and GitHub Git requests succeeded.
if ! curl --fail --silent --show-error --location --connect-timeout 10 --max-time 30 \
  --output "$TEMP_ROOT/workflow.json" \
  "https://api.github.com/repos/$GITHUB_REPO/actions/workflows/publish.yml"; then
  die 'Bootstrap remains published. The workflow lookup failed; check connectivity or GitHub workflow availability and rerun to resume setup without republishing.'
fi
node - "$TEMP_ROOT/workflow.json" <<'NODE'
const workflow = JSON.parse(require('node:fs').readFileSync(process.argv[2], 'utf8'));
if (workflow.state !== 'active' || workflow.path !== '.github/workflows/publish.yml') {
  throw new Error('The public publish.yml workflow must exist and be active before Trusted Publisher setup.');
}
NODE
step 'Confirm the existing publish.yml workflow is visible on GitHub and receives mirrored main pushes.'
note 'This checks release infrastructure only. This package does not need to be merged before bootstrap.'
if ! confirm 'The public release workflow is ready'; then exit 1; fi

stage "Configure the environment and Trusted Publisher"
open_url "https://github.com/$GITHUB_REPO/settings/environments"
step 'Create or confirm environment npm. Restrict deployment branches to branch main, with no required reviewers; the version PR is the approval boundary.'
if ! confirm 'The npm environment has those branch and approval settings'; then exit 1; fi
open_url "https://www.npmjs.com/package/$PACKAGE_NAME/access"
step "Open $PACKAGE_NAME → Settings → Trusted publishing → Add trusted publisher → GitHub Actions."
step 'Organization/user: LamplitIsles; repository: dsh-plugins; workflow filename: publish.yml; environment: npm.'
step 'Enable direct npm publish and save the connection.'
note 'The existing workflow grants id-token: write and publishes stable versions with provenance. No npm token secret is needed.'
if ! confirm "The Trusted Publisher connection is saved for $PACKAGE_NAME"; then exit 1; fi

stage "Hand off the first stable OIDC release"
say "Bootstrap complete: $PACKAGE_NAME@$BOOTSTRAP_VERSION is public under beta."
step 'Ask the agent to inspect the version on main and npm, then prepare the first stable version PR.'
note "A new manifest does not publish automatically. If main already records $STABLE_VERSION, the release PR must select a higher unpublished stable version."
note "If main has a prerelease baseline, a version PR to $STABLE_VERSION can trigger its stable release."
step 'Review and merge that PR in Forgejo. GitHub main publishes through the existing OIDC workflow; no tag or manual dispatch is needed.'
open_url "https://github.com/$GITHUB_REPO/actions/workflows/publish.yml"
say "After CI succeeds, verify the exact version selected by the PR with npm view $PACKAGE_NAME@<version> version --registry=$REGISTRY --prefer-online."
note 'This wizard does not change the stable version, create commits/PRs/tags, merge, or deploy.'
finish
say "Configured one package: $PACKAGE_NAME. Other workspace packages were not published."
say "Your checkout version and Git state are unchanged. The stable release is a separate version PR."
